### ISSUE TITLE
add to bower

### ISSUE THREAD

**Issue by pdeva** [gagiks/jquery-tbltree#1]
please add to bower repo

**Comment by gagiks** [comment]
I'm not familiar with what is bower repo, could you please provide more info?

**Comment by rodrigo2000** [comment]
Callback CREATE() function does not exist in your code.
In your documentation you have twice the EXPAND function. One have to change it COLLAPSE.

**Comment by gagiks** [comment]
For callback create please look to the example on page:
   http://gagiks.github.io/jquery-tbltree/examples/events.html

Regarding the second comment I didn't find issue in provided doc.

Thanks,
Gagik.
