### ISSUE TITLE
initially first level open

### ISSUE THREAD

**Issue by lavaraju** [gagiks/jquery-tbltree#3]
Hi,
    i want to expand my tbltree one level , but i can not achieve this using expand,showlevel call back functions please help me with code or example.

**Comment by gagiks** [comment]
Hello,

You can find an example here:
http://gagiks.github.io/jquery-tbltree/examples/levelPickers.html

The basic usage is to provide call the plugin as follows:
   `$( "#table1" ).tbltree({
            levelPicker: '#my-widget1'
     });`

the element with ID "my-widget1" is the container where you want to see the level picker buttons.

Hope this helps.

Gagik.
